insert into spot (id_spot, seat_number, type) values (1, 1, 'Avalon');
insert into spot (id_spot, seat_number, type) values (2, 2, 'S-Type');
insert into spot (id_spot, seat_number, type) values (3, 3, 'Tribute');
insert into spot (id_spot, seat_number, type) values (4, 4, 'Frontier');
insert into spot (id_spot, seat_number, type) values (5, 5, 'B-Series');
insert into spot (id_spot, seat_number, type) values (6, 6, 'Quattro');
insert into spot (id_spot, seat_number, type) values (7, 7, 'Mighty Max');
insert into spot (id_spot, seat_number, type) values (8, 8, 'Charger');
insert into spot (id_spot, seat_number, type) values (9, 9, 'DTS');
insert into spot (id_spot, seat_number, type) values (10, 10, 'RVR');
insert into spot (id_spot, seat_number, type) values (11, 11, 'Solara');
insert into spot (id_spot, seat_number, type) values (12, 12, 'Land Cruiser');
insert into spot (id_spot, seat_number, type) values (13, 13, '1 Series');
insert into spot (id_spot, seat_number, type) values (14, 14, 'S-Type');
insert into spot (id_spot, seat_number, type) values (15, 15, 'Grand Cherokee');
insert into spot (id_spot, seat_number, type) values (16, 16, 'Scoupe');
insert into spot (id_spot, seat_number, type) values (17, 17, 'Equinox');
insert into spot (id_spot, seat_number, type) values (18, 18, 'Explorer');
insert into spot (id_spot, seat_number, type) values (19, 19, 'IS');
insert into spot (id_spot, seat_number, type) values (20, 20, 'Discovery');
insert into spot (id_spot, seat_number, type) values (21, 21, 'LHS');
insert into spot (id_spot, seat_number, type) values (22, 22, 'R-Class');
insert into spot (id_spot, seat_number, type) values (23, 23, 'Corvette');
insert into spot (id_spot, seat_number, type) values (24, 24, 'Firebird Trans Am');
insert into spot (id_spot, seat_number, type) values (25, 25, 'Thunderbird');
insert into spot (id_spot, seat_number, type) values (26, 26, 'B-Series');
insert into spot (id_spot, seat_number, type) values (27, 27, 'Spectra');
insert into spot (id_spot, seat_number, type) values (28, 28, 'Versa');
insert into spot (id_spot, seat_number, type) values (29, 29, 'S2000');
insert into spot (id_spot, seat_number, type) values (30, 30, '1000');
insert into spot (id_spot, seat_number, type) values (31, 31, 'Flex');
insert into spot (id_spot, seat_number, type) values (32, 32, 'Neon');
insert into spot (id_spot, seat_number, type) values (33, 33, 'Solara');
insert into spot (id_spot, seat_number, type) values (34, 34, 'Civic');
insert into spot (id_spot, seat_number, type) values (35, 35, '57S');
insert into spot (id_spot, seat_number, type) values (36, 36, 'Jetta III');
insert into spot (id_spot, seat_number, type) values (37, 37, 'C-Class');
insert into spot (id_spot, seat_number, type) values (38, 38, 'Tundra');
insert into spot (id_spot, seat_number, type) values (39, 39, 'Camaro');
insert into spot (id_spot, seat_number, type) values (40, 40, 'Accord');
insert into spot (id_spot, seat_number, type) values (41, 41, 'E150');
insert into spot (id_spot, seat_number, type) values (42, 42, 'Rio');
insert into spot (id_spot, seat_number, type) values (43, 43, 'Sable');
insert into spot (id_spot, seat_number, type) values (44, 44, 'M3');
insert into spot (id_spot, seat_number, type) values (45, 45, 'MX-5');
insert into spot (id_spot, seat_number, type) values (46, 46, 'Malibu');
insert into spot (id_spot, seat_number, type) values (47, 47, 'RX-7');
insert into spot (id_spot, seat_number, type) values (48, 48, 'Legacy');
insert into spot (id_spot, seat_number, type) values (49, 49, '7 Series');
insert into spot (id_spot, seat_number, type) values (50, 50, 'Sierra 1500');
insert into spot (id_spot, seat_number, type) values (51, 51, 'E-Class');
insert into spot (id_spot, seat_number, type) values (52, 52, 'Discovery Series II');
insert into spot (id_spot, seat_number, type) values (53, 53, 'Navigator');
insert into spot (id_spot, seat_number, type) values (54, 54, 'Spirit');
insert into spot (id_spot, seat_number, type) values (55, 55, '911');
insert into spot (id_spot, seat_number, type) values (56, 56, 'Crosstour');
insert into spot (id_spot, seat_number, type) values (57, 57, 'Corvette');
insert into spot (id_spot, seat_number, type) values (58, 58, 'Lancer Evolution');
insert into spot (id_spot, seat_number, type) values (59, 59, 'Ranger');
insert into spot (id_spot, seat_number, type) values (60, 60, 'Exige');
insert into spot (id_spot, seat_number, type) values (61, 61, 'Explorer Sport Trac');
insert into spot (id_spot, seat_number, type) values (62, 62, 'Prizm');
insert into spot (id_spot, seat_number, type) values (63, 63, 'C8 Spyder');
insert into spot (id_spot, seat_number, type) values (64, 64, 'Roadmaster');
insert into spot (id_spot, seat_number, type) values (65, 65, 'Freelander');
insert into spot (id_spot, seat_number, type) values (66, 66, 'MX-5');
insert into spot (id_spot, seat_number, type) values (67, 67, '5 Series');
insert into spot (id_spot, seat_number, type) values (68, 68, 'Corvette');
insert into spot (id_spot, seat_number, type) values (69, 69, 'Cherokee');
insert into spot (id_spot, seat_number, type) values (70, 70, 'Land Cruiser');
insert into spot (id_spot, seat_number, type) values (71, 71, '80/90');
insert into spot (id_spot, seat_number, type) values (72, 72, 'Grand Prix');
insert into spot (id_spot, seat_number, type) values (73, 73, 'I');
insert into spot (id_spot, seat_number, type) values (74, 74, 'Vantage');
insert into spot (id_spot, seat_number, type) values (75, 75, 'Caravan');
insert into spot (id_spot, seat_number, type) values (76, 76, 'Voyager');
insert into spot (id_spot, seat_number, type) values (77, 77, 'LS');
insert into spot (id_spot, seat_number, type) values (78, 78, 'Genesis');
insert into spot (id_spot, seat_number, type) values (79, 79, 'Explorer');
insert into spot (id_spot, seat_number, type) values (80, 80, 'Equus');
insert into spot (id_spot, seat_number, type) values (81, 81, 'Equus');
insert into spot (id_spot, seat_number, type) values (82, 82, 'Thunderbird');
insert into spot (id_spot, seat_number, type) values (83, 83, '9-3');
insert into spot (id_spot, seat_number, type) values (84, 84, 'Bonneville');
insert into spot (id_spot, seat_number, type) values (85, 85, 'Ram 2500');
insert into spot (id_spot, seat_number, type) values (86, 86, 'Accent');
insert into spot (id_spot, seat_number, type) values (87, 87, 'Mazda6');
insert into spot (id_spot, seat_number, type) values (88, 88, 'I');
insert into spot (id_spot, seat_number, type) values (89, 89, 'Regal');
insert into spot (id_spot, seat_number, type) values (90, 90, '57');
insert into spot (id_spot, seat_number, type) values (91, 91, 'Z4');
insert into spot (id_spot, seat_number, type) values (92, 92, 'Contour');
insert into spot (id_spot, seat_number, type) values (93, 93, 'X3');
insert into spot (id_spot, seat_number, type) values (94, 94, 'Gallardo');
insert into spot (id_spot, seat_number, type) values (95, 95, 'Samurai');
insert into spot (id_spot, seat_number, type) values (96, 96, 'Lancer');
insert into spot (id_spot, seat_number, type) values (97, 97, 'Azure');
insert into spot (id_spot, seat_number, type) values (98, 98, 'NSX');
insert into spot (id_spot, seat_number, type) values (99, 99, 'F250');
insert into spot (id_spot, seat_number, type) values (100, 100, 'Accent');
insert into spot (id_spot, seat_number, type) values (101, 101, 'Marquis');
insert into spot (id_spot, seat_number, type) values (102, 102, 'TSX');
insert into spot (id_spot, seat_number, type) values (103, 103, 'Panamera');
insert into spot (id_spot, seat_number, type) values (104, 104, 'Lancer Evolution');
insert into spot (id_spot, seat_number, type) values (105, 105, 'CR-X');
insert into spot (id_spot, seat_number, type) values (106, 106, 'Accord');
insert into spot (id_spot, seat_number, type) values (107, 107, 'Mark LT');
insert into spot (id_spot, seat_number, type) values (108, 108, 'Quest');
insert into spot (id_spot, seat_number, type) values (109, 109, 'Ascender');
insert into spot (id_spot, seat_number, type) values (110, 110, 'Grand Voyager');
insert into spot (id_spot, seat_number, type) values (111, 111, 'E-Series');
insert into spot (id_spot, seat_number, type) values (112, 112, 'TrailBlazer');
insert into spot (id_spot, seat_number, type) values (113, 113, 'V12 Vantage');
insert into spot (id_spot, seat_number, type) values (114, 114, 'Eclipse');
insert into spot (id_spot, seat_number, type) values (115, 115, 'F150');
insert into spot (id_spot, seat_number, type) values (116, 116, 'Esprit');
insert into spot (id_spot, seat_number, type) values (117, 117, 'Q');
insert into spot (id_spot, seat_number, type) values (118, 118, 'Boxster');
insert into spot (id_spot, seat_number, type) values (119, 119, 'QX');
insert into spot (id_spot, seat_number, type) values (120, 120, 'CX-9');
insert into spot (id_spot, seat_number, type) values (121, 121, 'Montana');
insert into spot (id_spot, seat_number, type) values (122, 122, 'Suburban 1500');
insert into spot (id_spot, seat_number, type) values (123, 123, 'GTI');
insert into spot (id_spot, seat_number, type) values (124, 124, 'Forenza');
insert into spot (id_spot, seat_number, type) values (125, 125, 'GTI');
insert into spot (id_spot, seat_number, type) values (126, 126, '1500');
insert into spot (id_spot, seat_number, type) values (127, 127, 'Pathfinder');
insert into spot (id_spot, seat_number, type) values (128, 128, 'Space');
insert into spot (id_spot, seat_number, type) values (129, 129, 'V50');
insert into spot (id_spot, seat_number, type) values (130, 130, 'W201');
insert into spot (id_spot, seat_number, type) values (131, 131, 'Dakota Club');
insert into spot (id_spot, seat_number, type) values (132, 132, 'S-Series');
insert into spot (id_spot, seat_number, type) values (133, 133, 'EX');
insert into spot (id_spot, seat_number, type) values (134, 134, 'F150');
insert into spot (id_spot, seat_number, type) values (135, 135, '300C');
insert into spot (id_spot, seat_number, type) values (136, 136, 'Savana 3500');
insert into spot (id_spot, seat_number, type) values (137, 137, 'Wrangler');
insert into spot (id_spot, seat_number, type) values (138, 138, 'Mustang');
insert into spot (id_spot, seat_number, type) values (139, 139, 'Firebird');
insert into spot (id_spot, seat_number, type) values (140, 140, 'Firebird');
insert into spot (id_spot, seat_number, type) values (141, 141, 'Eurovan');
insert into spot (id_spot, seat_number, type) values (142, 142, 'Century');
insert into spot (id_spot, seat_number, type) values (143, 143, 'Solstice');
insert into spot (id_spot, seat_number, type) values (144, 144, 'E350');
insert into spot (id_spot, seat_number, type) values (145, 145, '500SEL');
insert into spot (id_spot, seat_number, type) values (146, 146, 'Suburban 1500');
insert into spot (id_spot, seat_number, type) values (147, 147, 'LX');
insert into spot (id_spot, seat_number, type) values (148, 148, 'Pilot');
insert into spot (id_spot, seat_number, type) values (149, 149, 'Mystique');
insert into spot (id_spot, seat_number, type) values (150, 150, 'S-Class');
insert into spot (id_spot, seat_number, type) values (151, 151, 'V90');
insert into spot (id_spot, seat_number, type) values (152, 152, 'RX-7');
insert into spot (id_spot, seat_number, type) values (153, 153, 'Town Car');
insert into spot (id_spot, seat_number, type) values (154, 154, 'Jetta');
insert into spot (id_spot, seat_number, type) values (155, 155, 'Ranger');
insert into spot (id_spot, seat_number, type) values (156, 156, 'MX-5');
insert into spot (id_spot, seat_number, type) values (157, 157, 'A8');
insert into spot (id_spot, seat_number, type) values (158, 158, 'Ram Van 3500');
insert into spot (id_spot, seat_number, type) values (159, 159, 'Ram Van 2500');
insert into spot (id_spot, seat_number, type) values (160, 160, '2500 Club Coupe');
insert into spot (id_spot, seat_number, type) values (161, 161, 'Previa');
insert into spot (id_spot, seat_number, type) values (162, 162, 'Sienna');
insert into spot (id_spot, seat_number, type) values (163, 163, 'Tredia');
insert into spot (id_spot, seat_number, type) values (164, 164, 'Freelander');
insert into spot (id_spot, seat_number, type) values (165, 165, '5000S');
insert into spot (id_spot, seat_number, type) values (166, 166, 'RX');
insert into spot (id_spot, seat_number, type) values (167, 167, 'Camry');
insert into spot (id_spot, seat_number, type) values (168, 168, 'FX');
insert into spot (id_spot, seat_number, type) values (169, 169, '300M');
insert into spot (id_spot, seat_number, type) values (170, 170, 'Jetta');
insert into spot (id_spot, seat_number, type) values (171, 171, 'Land Cruiser');
insert into spot (id_spot, seat_number, type) values (172, 172, 'Caravan');
insert into spot (id_spot, seat_number, type) values (173, 173, 'Lynx');
insert into spot (id_spot, seat_number, type) values (174, 174, 'Econoline E250');
insert into spot (id_spot, seat_number, type) values (175, 175, 'M5');
insert into spot (id_spot, seat_number, type) values (176, 176, '190E');
insert into spot (id_spot, seat_number, type) values (177, 177, '300ZX');
insert into spot (id_spot, seat_number, type) values (178, 178, 'Monte Carlo');
insert into spot (id_spot, seat_number, type) values (179, 179, 'Murano');
insert into spot (id_spot, seat_number, type) values (180, 180, 'Dakota');
insert into spot (id_spot, seat_number, type) values (181, 181, 'Accord');
insert into spot (id_spot, seat_number, type) values (182, 182, 'Mirage');
insert into spot (id_spot, seat_number, type) values (183, 183, 'Rio');
insert into spot (id_spot, seat_number, type) values (184, 184, 'B-Series Plus');
insert into spot (id_spot, seat_number, type) values (185, 185, 'S40');
insert into spot (id_spot, seat_number, type) values (186, 186, 'Firebird Trans Am');
insert into spot (id_spot, seat_number, type) values (187, 187, 'Seville');
insert into spot (id_spot, seat_number, type) values (188, 188, 'Explorer');
insert into spot (id_spot, seat_number, type) values (189, 189, 'Ram 1500');
insert into spot (id_spot, seat_number, type) values (190, 190, 'Civic');
insert into spot (id_spot, seat_number, type) values (191, 191, 'E-Class');
insert into spot (id_spot, seat_number, type) values (192, 192, 'A5');
insert into spot (id_spot, seat_number, type) values (193, 193, 'Corvette');
insert into spot (id_spot, seat_number, type) values (194, 194, 'XK Series');
insert into spot (id_spot, seat_number, type) values (195, 195, 'Defender');
insert into spot (id_spot, seat_number, type) values (196, 196, 'F350');
insert into spot (id_spot, seat_number, type) values (197, 197, 'Town Car');
insert into spot (id_spot, seat_number, type) values (198, 198, 'Expedition EL');
insert into spot (id_spot, seat_number, type) values (199, 199, 'Eldorado');
insert into spot (id_spot, seat_number, type) values (200, 200, 'Cayenne');
insert into spot (id_spot, seat_number, type) values (201, 201, '5 Series');
insert into spot (id_spot, seat_number, type) values (202, 202, 'RX');
insert into spot (id_spot, seat_number, type) values (203, 203, 'Cirrus');
insert into spot (id_spot, seat_number, type) values (204, 204, 'SRX');
insert into spot (id_spot, seat_number, type) values (205, 205, 'Elantra');
insert into spot (id_spot, seat_number, type) values (206, 206, 'Traverse');
insert into spot (id_spot, seat_number, type) values (207, 207, 'Corvette');
insert into spot (id_spot, seat_number, type) values (208, 208, 'Arnage');
insert into spot (id_spot, seat_number, type) values (209, 209, 'Imperial');
insert into spot (id_spot, seat_number, type) values (210, 210, 'Topaz');
insert into spot (id_spot, seat_number, type) values (211, 211, 'F-Series');
insert into spot (id_spot, seat_number, type) values (212, 212, 'Mirage');
insert into spot (id_spot, seat_number, type) values (213, 213, 'MP4-12C');
insert into spot (id_spot, seat_number, type) values (214, 214, 'Caravan');
insert into spot (id_spot, seat_number, type) values (215, 215, 'Dakota Club');
insert into spot (id_spot, seat_number, type) values (216, 216, '599 GTB Fiorano');
insert into spot (id_spot, seat_number, type) values (217, 217, 'Sprinter 2500');
insert into spot (id_spot, seat_number, type) values (218, 218, 'Tundra');
insert into spot (id_spot, seat_number, type) values (219, 219, 'Civic');
insert into spot (id_spot, seat_number, type) values (220, 220, 'Sienna');
insert into spot (id_spot, seat_number, type) values (221, 221, 'Sonoma');
insert into spot (id_spot, seat_number, type) values (222, 222, '5 Series');
insert into spot (id_spot, seat_number, type) values (223, 223, 'Tacoma');
insert into spot (id_spot, seat_number, type) values (224, 224, 'Aveo');
insert into spot (id_spot, seat_number, type) values (225, 225, 'Yukon');
insert into spot (id_spot, seat_number, type) values (226, 226, 'Grand Prix');
insert into spot (id_spot, seat_number, type) values (227, 227, 'M Roadster');
insert into spot (id_spot, seat_number, type) values (228, 228, 'Focus');
insert into spot (id_spot, seat_number, type) values (229, 229, 'LeBaron');
insert into spot (id_spot, seat_number, type) values (230, 230, 'MDX');
insert into spot (id_spot, seat_number, type) values (231, 231, '645');
insert into spot (id_spot, seat_number, type) values (232, 232, 'NSX');
insert into spot (id_spot, seat_number, type) values (233, 233, 'ZDX');
insert into spot (id_spot, seat_number, type) values (234, 234, 'Cougar');
insert into spot (id_spot, seat_number, type) values (235, 235, 'D250');
insert into spot (id_spot, seat_number, type) values (236, 236, 'RAV4');
insert into spot (id_spot, seat_number, type) values (237, 237, 'Range Rover');
insert into spot (id_spot, seat_number, type) values (238, 238, 'S4');
insert into spot (id_spot, seat_number, type) values (239, 239, 'S-Series');
insert into spot (id_spot, seat_number, type) values (240, 240, 'XF');
insert into spot (id_spot, seat_number, type) values (241, 241, 'Prius');
insert into spot (id_spot, seat_number, type) values (242, 242, '911');
insert into spot (id_spot, seat_number, type) values (243, 243, 'Raider');
insert into spot (id_spot, seat_number, type) values (244, 244, 'Sienna');
insert into spot (id_spot, seat_number, type) values (245, 245, 'Rally Wagon 2500');
insert into spot (id_spot, seat_number, type) values (246, 246, 'Lucerne');
insert into spot (id_spot, seat_number, type) values (247, 247, '323');
insert into spot (id_spot, seat_number, type) values (248, 248, 'Ridgeline');
insert into spot (id_spot, seat_number, type) values (249, 249, 'Endeavor');
insert into spot (id_spot, seat_number, type) values (250, 250, '850');
insert into spot (id_spot, seat_number, type) values (251, 251, 'Jimmy');
insert into spot (id_spot, seat_number, type) values (252, 252, 'Silverado 3500');
insert into spot (id_spot, seat_number, type) values (253, 253, 'Phantom');
insert into spot (id_spot, seat_number, type) values (254, 254, 'Continental Mark VII');
insert into spot (id_spot, seat_number, type) values (255, 255, 'Sportvan G30');
insert into spot (id_spot, seat_number, type) values (256, 256, 'Rabbit');
insert into spot (id_spot, seat_number, type) values (257, 257, 'Daewoo Lacetti');
insert into spot (id_spot, seat_number, type) values (258, 258, 'M5');
insert into spot (id_spot, seat_number, type) values (259, 259, 'Suburban 1500');
insert into spot (id_spot, seat_number, type) values (260, 260, 'Escalade EXT');
insert into spot (id_spot, seat_number, type) values (261, 261, 'F250');
insert into spot (id_spot, seat_number, type) values (262, 262, 'Astro');
insert into spot (id_spot, seat_number, type) values (263, 263, 'Q');
insert into spot (id_spot, seat_number, type) values (264, 264, 'Bronco');
insert into spot (id_spot, seat_number, type) values (265, 265, 'Brat');
insert into spot (id_spot, seat_number, type) values (266, 266, 'M Roadster');
insert into spot (id_spot, seat_number, type) values (267, 267, 'Jetta');
insert into spot (id_spot, seat_number, type) values (268, 268, '4Runner');
insert into spot (id_spot, seat_number, type) values (269, 269, 'Corvette');
insert into spot (id_spot, seat_number, type) values (270, 270, 'Tahoe');
insert into spot (id_spot, seat_number, type) values (271, 271, 'Solara');
insert into spot (id_spot, seat_number, type) values (272, 272, 'Passport');
insert into spot (id_spot, seat_number, type) values (273, 273, 'Firebird');
insert into spot (id_spot, seat_number, type) values (274, 274, 'F350');
insert into spot (id_spot, seat_number, type) values (275, 275, 'QX56');
insert into spot (id_spot, seat_number, type) values (276, 276, 'Dakota');
insert into spot (id_spot, seat_number, type) values (277, 277, 'Liberty');
insert into spot (id_spot, seat_number, type) values (278, 278, 'DeVille');
insert into spot (id_spot, seat_number, type) values (279, 279, 'Mustang');
insert into spot (id_spot, seat_number, type) values (280, 280, 'MPV');
insert into spot (id_spot, seat_number, type) values (281, 281, 'Solara');
insert into spot (id_spot, seat_number, type) values (282, 282, 'S60');
insert into spot (id_spot, seat_number, type) values (283, 283, 'Murciélago');
insert into spot (id_spot, seat_number, type) values (284, 284, 'Gemini');
insert into spot (id_spot, seat_number, type) values (285, 285, 'JX');
insert into spot (id_spot, seat_number, type) values (286, 286, 'H2');
insert into spot (id_spot, seat_number, type) values (287, 287, 'Familia');
insert into spot (id_spot, seat_number, type) values (288, 288, 'S10');
insert into spot (id_spot, seat_number, type) values (289, 289, 'Mountaineer');
insert into spot (id_spot, seat_number, type) values (290, 290, 'Q');
insert into spot (id_spot, seat_number, type) values (291, 291, '500SEL');
insert into spot (id_spot, seat_number, type) values (292, 292, 'B-Series');
insert into spot (id_spot, seat_number, type) values (293, 293, 'XJ Series');
insert into spot (id_spot, seat_number, type) values (294, 294, 'Ram Van B350');
insert into spot (id_spot, seat_number, type) values (295, 295, 'Montero');
insert into spot (id_spot, seat_number, type) values (296, 296, 'L-Series');
insert into spot (id_spot, seat_number, type) values (297, 297, '1500');
insert into spot (id_spot, seat_number, type) values (298, 298, 'Sierra 2500');
insert into spot (id_spot, seat_number, type) values (299, 299, 'Suburban');
insert into spot (id_spot, seat_number, type) values (300, 300, 'Accord');
insert into spot (id_spot, seat_number, type) values (301, 301, 'S5');
insert into spot (id_spot, seat_number, type) values (302, 302, 'C-MAX Hybrid');
insert into spot (id_spot, seat_number, type) values (303, 303, 'Yaris');
insert into spot (id_spot, seat_number, type) values (304, 304, 'Seville');
insert into spot (id_spot, seat_number, type) values (305, 305, 'GT350');
insert into spot (id_spot, seat_number, type) values (306, 306, 'Suburban 1500');
insert into spot (id_spot, seat_number, type) values (307, 307, 'S4');
insert into spot (id_spot, seat_number, type) values (308, 308, 'Ram 2500');
insert into spot (id_spot, seat_number, type) values (309, 309, 'Integra');
insert into spot (id_spot, seat_number, type) values (310, 310, 'Mirage');
insert into spot (id_spot, seat_number, type) values (311, 311, 'Grand Marquis');
insert into spot (id_spot, seat_number, type) values (312, 312, 'Mark VII');
insert into spot (id_spot, seat_number, type) values (313, 313, 'Econoline E350');
insert into spot (id_spot, seat_number, type) values (314, 314, 'Monte Carlo');
insert into spot (id_spot, seat_number, type) values (315, 315, 'Town Car');
insert into spot (id_spot, seat_number, type) values (316, 316, '9-5');
insert into spot (id_spot, seat_number, type) values (317, 317, 'Topaz');
insert into spot (id_spot, seat_number, type) values (318, 318, 'S-Series');
insert into spot (id_spot, seat_number, type) values (319, 319, 'F150');
insert into spot (id_spot, seat_number, type) values (320, 320, '928');
insert into spot (id_spot, seat_number, type) values (321, 321, 'SC');
insert into spot (id_spot, seat_number, type) values (322, 322, '3 Series');
insert into spot (id_spot, seat_number, type) values (323, 323, 'Lumina');
insert into spot (id_spot, seat_number, type) values (324, 324, 'Grand Cherokee');
insert into spot (id_spot, seat_number, type) values (325, 325, 'M3');
insert into spot (id_spot, seat_number, type) values (326, 326, 'B-Series');
insert into spot (id_spot, seat_number, type) values (327, 327, '5000CS');
insert into spot (id_spot, seat_number, type) values (328, 328, 'XLR-V');
insert into spot (id_spot, seat_number, type) values (329, 329, 'Bravada');
insert into spot (id_spot, seat_number, type) values (330, 330, 'Durango');
insert into spot (id_spot, seat_number, type) values (331, 331, 'Savana 1500');
insert into spot (id_spot, seat_number, type) values (332, 332, 'Ram Van B150');
insert into spot (id_spot, seat_number, type) values (333, 333, 'rio');
insert into spot (id_spot, seat_number, type) values (334, 334, 'RX-7');
insert into spot (id_spot, seat_number, type) values (335, 335, 'Cordia');
insert into spot (id_spot, seat_number, type) values (336, 336, 'Ram 3500');
insert into spot (id_spot, seat_number, type) values (337, 337, 'Mirage');
insert into spot (id_spot, seat_number, type) values (338, 338, 'Sequoia');
insert into spot (id_spot, seat_number, type) values (339, 339, 'Camry');
insert into spot (id_spot, seat_number, type) values (340, 340, '6000');
insert into spot (id_spot, seat_number, type) values (341, 341, 'MKT');
insert into spot (id_spot, seat_number, type) values (342, 342, 'S-Class');
insert into spot (id_spot, seat_number, type) values (343, 343, 'Firebird');
insert into spot (id_spot, seat_number, type) values (344, 344, 'Sephia');
insert into spot (id_spot, seat_number, type) values (345, 345, 'E-Class');
insert into spot (id_spot, seat_number, type) values (346, 346, 'T100');
insert into spot (id_spot, seat_number, type) values (347, 347, 'S80');
insert into spot (id_spot, seat_number, type) values (348, 348, 'Grand Marquis');
insert into spot (id_spot, seat_number, type) values (349, 349, 'Alero');
insert into spot (id_spot, seat_number, type) values (350, 350, 'Swift');
insert into spot (id_spot, seat_number, type) values (351, 351, 'XC70');
insert into spot (id_spot, seat_number, type) values (352, 352, 'Roadster');
insert into spot (id_spot, seat_number, type) values (353, 353, 'LX');
insert into spot (id_spot, seat_number, type) values (354, 354, 'NSX');
insert into spot (id_spot, seat_number, type) values (355, 355, 'Savana 3500');
insert into spot (id_spot, seat_number, type) values (356, 356, 'Jetta');
insert into spot (id_spot, seat_number, type) values (357, 357, 'Mazda6');
insert into spot (id_spot, seat_number, type) values (358, 358, '300');
insert into spot (id_spot, seat_number, type) values (359, 359, 'Countryman');
insert into spot (id_spot, seat_number, type) values (360, 360, 'Hombre Space');
insert into spot (id_spot, seat_number, type) values (361, 361, 'GS');
insert into spot (id_spot, seat_number, type) values (362, 362, 'Envoy');
insert into spot (id_spot, seat_number, type) values (363, 363, '350Z');
insert into spot (id_spot, seat_number, type) values (364, 364, 'Range Rover');
insert into spot (id_spot, seat_number, type) values (365, 365, 'Viper RT/10');
insert into spot (id_spot, seat_number, type) values (366, 366, 'Terrain');
insert into spot (id_spot, seat_number, type) values (367, 367, 'RSX');
insert into spot (id_spot, seat_number, type) values (368, 368, 'Trans Sport');
insert into spot (id_spot, seat_number, type) values (369, 369, 'Rio5');
insert into spot (id_spot, seat_number, type) values (370, 370, 'Fusion');
insert into spot (id_spot, seat_number, type) values (371, 371, 'Highlander Hybrid');
insert into spot (id_spot, seat_number, type) values (372, 372, 'CX-9');
insert into spot (id_spot, seat_number, type) values (373, 373, 'S10');
insert into spot (id_spot, seat_number, type) values (374, 374, 'Explorer');
insert into spot (id_spot, seat_number, type) values (375, 375, 'M-Class');
insert into spot (id_spot, seat_number, type) values (376, 376, 'SLK-Class');
insert into spot (id_spot, seat_number, type) values (377, 377, 'xB');
insert into spot (id_spot, seat_number, type) values (378, 378, '80');
insert into spot (id_spot, seat_number, type) values (379, 379, 'Accord Crosstour');
insert into spot (id_spot, seat_number, type) values (380, 380, 'T100');
insert into spot (id_spot, seat_number, type) values (381, 381, 'IS');
insert into spot (id_spot, seat_number, type) values (382, 382, 'Mustang');
insert into spot (id_spot, seat_number, type) values (383, 383, 'Mountaineer');
insert into spot (id_spot, seat_number, type) values (384, 384, 'Xtra');
insert into spot (id_spot, seat_number, type) values (385, 385, '5 Series');
insert into spot (id_spot, seat_number, type) values (386, 386, 'MKZ');
insert into spot (id_spot, seat_number, type) values (387, 387, 'Rodeo');
insert into spot (id_spot, seat_number, type) values (388, 388, 'Express 1500');
insert into spot (id_spot, seat_number, type) values (389, 389, 'Prizm');
insert into spot (id_spot, seat_number, type) values (390, 390, 'Frontier');
insert into spot (id_spot, seat_number, type) values (391, 391, 'Miata MX-5');
insert into spot (id_spot, seat_number, type) values (392, 392, 'Diablo');
insert into spot (id_spot, seat_number, type) values (393, 393, 'Taurus');
insert into spot (id_spot, seat_number, type) values (394, 394, 'Corvette');
insert into spot (id_spot, seat_number, type) values (395, 395, '5 Series');
insert into spot (id_spot, seat_number, type) values (396, 396, 'Sierra 1500');
insert into spot (id_spot, seat_number, type) values (397, 397, 'Wrangler');
insert into spot (id_spot, seat_number, type) values (398, 398, 'Aspire');
insert into spot (id_spot, seat_number, type) values (399, 399, 'Town Car');
insert into spot (id_spot, seat_number, type) values (400, 400, 'V70');
insert into spot (id_spot, seat_number, type) values (401, 401, '9-3');
insert into spot (id_spot, seat_number, type) values (402, 402, 'Pathfinder');
insert into spot (id_spot, seat_number, type) values (403, 403, 'Diablo');
insert into spot (id_spot, seat_number, type) values (404, 404, 'Outlook');
insert into spot (id_spot, seat_number, type) values (405, 405, 'Corvette');
insert into spot (id_spot, seat_number, type) values (406, 406, 'Bravada');
insert into spot (id_spot, seat_number, type) values (407, 407, 'XF');
insert into spot (id_spot, seat_number, type) values (408, 408, 'Celica');
insert into spot (id_spot, seat_number, type) values (409, 409, 'Ram 3500');
insert into spot (id_spot, seat_number, type) values (410, 410, 'Topaz');
insert into spot (id_spot, seat_number, type) values (411, 411, '911');
insert into spot (id_spot, seat_number, type) values (412, 412, 'TL');
insert into spot (id_spot, seat_number, type) values (413, 413, '7 Series');
insert into spot (id_spot, seat_number, type) values (414, 414, 'Grand Prix');
insert into spot (id_spot, seat_number, type) values (415, 415, '9-3');
insert into spot (id_spot, seat_number, type) values (416, 416, 'Eldorado');
insert into spot (id_spot, seat_number, type) values (417, 417, 'Tacoma');
insert into spot (id_spot, seat_number, type) values (418, 418, 'Chariot');
insert into spot (id_spot, seat_number, type) values (419, 419, 'Brat');
insert into spot (id_spot, seat_number, type) values (420, 420, 'Yaris');
insert into spot (id_spot, seat_number, type) values (421, 421, 'LeMans');
insert into spot (id_spot, seat_number, type) values (422, 422, 'Alcyone SVX');
insert into spot (id_spot, seat_number, type) values (423, 423, 'B-Series');
insert into spot (id_spot, seat_number, type) values (424, 424, 'Matrix');
insert into spot (id_spot, seat_number, type) values (425, 425, 'E-Class');
insert into spot (id_spot, seat_number, type) values (426, 426, 'Forester');
insert into spot (id_spot, seat_number, type) values (427, 427, 'B-Series');
insert into spot (id_spot, seat_number, type) values (428, 428, 'Sunfire');
insert into spot (id_spot, seat_number, type) values (429, 429, 'Neon');
insert into spot (id_spot, seat_number, type) values (430, 430, 'Quattroporte');
insert into spot (id_spot, seat_number, type) values (431, 431, 'Brat');
insert into spot (id_spot, seat_number, type) values (432, 432, 'Eurovan');
insert into spot (id_spot, seat_number, type) values (433, 433, 'S60');
insert into spot (id_spot, seat_number, type) values (434, 434, 'E-Class');
insert into spot (id_spot, seat_number, type) values (435, 435, 'F150');
insert into spot (id_spot, seat_number, type) values (436, 436, 'Fiero');
insert into spot (id_spot, seat_number, type) values (437, 437, 'Sentra');
insert into spot (id_spot, seat_number, type) values (438, 438, 'Focus ST');
insert into spot (id_spot, seat_number, type) values (439, 439, 'Vibe');
insert into spot (id_spot, seat_number, type) values (440, 440, 'RAV4');
insert into spot (id_spot, seat_number, type) values (441, 441, 'Truck');
insert into spot (id_spot, seat_number, type) values (442, 442, 'G35');
insert into spot (id_spot, seat_number, type) values (443, 443, 'Silverado 3500');
insert into spot (id_spot, seat_number, type) values (444, 444, 'Crown Victoria');
insert into spot (id_spot, seat_number, type) values (445, 445, 'Amigo');
insert into spot (id_spot, seat_number, type) values (446, 446, 'Sportage');
insert into spot (id_spot, seat_number, type) values (447, 447, 'SLX');
insert into spot (id_spot, seat_number, type) values (448, 448, 'Venture');
insert into spot (id_spot, seat_number, type) values (449, 449, 'Silverado 3500');
insert into spot (id_spot, seat_number, type) values (450, 450, 'Firebird');
insert into spot (id_spot, seat_number, type) values (451, 451, '500E');
insert into spot (id_spot, seat_number, type) values (452, 452, 'Sienna');
insert into spot (id_spot, seat_number, type) values (453, 453, 'Ram Wagon B350');
insert into spot (id_spot, seat_number, type) values (454, 454, 'Forester');
insert into spot (id_spot, seat_number, type) values (455, 455, 'xB');
insert into spot (id_spot, seat_number, type) values (456, 456, '100');
insert into spot (id_spot, seat_number, type) values (457, 457, 'S10');
insert into spot (id_spot, seat_number, type) values (458, 458, 'Cooper Clubman');
insert into spot (id_spot, seat_number, type) values (459, 459, 'Sonoma Club Coupe');
insert into spot (id_spot, seat_number, type) values (460, 460, 'Spectra');
insert into spot (id_spot, seat_number, type) values (461, 461, 'SL-Class');
insert into spot (id_spot, seat_number, type) values (462, 462, 'Pajero');
insert into spot (id_spot, seat_number, type) values (463, 463, 'Solstice');
insert into spot (id_spot, seat_number, type) values (464, 464, 'Accord');
insert into spot (id_spot, seat_number, type) values (465, 465, 'Diamante');
insert into spot (id_spot, seat_number, type) values (466, 466, 'riolet');
insert into spot (id_spot, seat_number, type) values (467, 467, 'GTI');
insert into spot (id_spot, seat_number, type) values (468, 468, 'Thunderbird');
insert into spot (id_spot, seat_number, type) values (469, 469, 'Rogue');
insert into spot (id_spot, seat_number, type) values (470, 470, 'New Beetle');
insert into spot (id_spot, seat_number, type) values (471, 471, 'XJ Series');
insert into spot (id_spot, seat_number, type) values (472, 472, 'Clubman');
insert into spot (id_spot, seat_number, type) values (473, 473, 'Grand Prix');
insert into spot (id_spot, seat_number, type) values (474, 474, 'Accord');
insert into spot (id_spot, seat_number, type) values (475, 475, 'Quest');
insert into spot (id_spot, seat_number, type) values (476, 476, '7 Series');
insert into spot (id_spot, seat_number, type) values (477, 477, 'Yukon');
insert into spot (id_spot, seat_number, type) values (478, 478, 'Silverado');
insert into spot (id_spot, seat_number, type) values (479, 479, 'F150');
insert into spot (id_spot, seat_number, type) values (480, 480, 'G3');
insert into spot (id_spot, seat_number, type) values (481, 481, '4000CS Quattro');
insert into spot (id_spot, seat_number, type) values (482, 482, '6 Series');
insert into spot (id_spot, seat_number, type) values (483, 483, 'LS');
insert into spot (id_spot, seat_number, type) values (484, 484, 'Rio');
insert into spot (id_spot, seat_number, type) values (485, 485, 'Express 2500');
insert into spot (id_spot, seat_number, type) values (486, 486, 'Tracker');
insert into spot (id_spot, seat_number, type) values (487, 487, 'Navigator L');
insert into spot (id_spot, seat_number, type) values (488, 488, 'Landaulet');
insert into spot (id_spot, seat_number, type) values (489, 489, '6000');
insert into spot (id_spot, seat_number, type) values (490, 490, 'Phantom');
insert into spot (id_spot, seat_number, type) values (491, 491, 'Mountaineer');
insert into spot (id_spot, seat_number, type) values (492, 492, 'Firebird');
insert into spot (id_spot, seat_number, type) values (493, 493, '9-3');
insert into spot (id_spot, seat_number, type) values (494, 494, 'Lucerne');
insert into spot (id_spot, seat_number, type) values (495, 495, 'Ram 2500');
insert into spot (id_spot, seat_number, type) values (496, 496, 'LS');
insert into spot (id_spot, seat_number, type) values (497, 497, 'Silverado 1500');
insert into spot (id_spot, seat_number, type) values (498, 498, 'Versa');
insert into spot (id_spot, seat_number, type) values (499, 499, 'Century');
insert into spot (id_spot, seat_number, type) values (500, 500, 'Grand Caravan');
